global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

#api:
#  dashboard: true

entryPoints:
# http:
#   address: ":80"
  https:
    address: ":443"
    asDefault: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
